import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

WATCHLIST_FILE = "watchlist.csv"
DB_FILE = "database.db"

MIN_VOLUME = 500
MIN_NOTIONAL = 25000
MIN_VOL_OI_RATIO = 8.0
MIN_RELATIVE_VOL = 5.0
MAX_TICKERS = 50 
